Lister.Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Lister.Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}


Lister.Web/Pages/Index.cshtml.cs
using Lister.Library.Interfaces;
using Lister.Library.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Lister.Web.Pages;

[ValidateAntiForgeryToken]
public class IndexModel : PageModel
{
    private IToDoService _todos;

    public IndexModel(IToDoService todos)
    {
        _todos = todos;
    }

    public List<ToDoModel> AllToDos { get; set; } = [];

    [BindProperty(SupportsGet = true)]
    public string NewToDo { get; set; } = "";

    public IActionResult OnGet()
    {
        AllToDos = _todos.GetAllToDos();

        return Page();
    }

    public IActionResult OnPostComplete(int id)
    {
        _todos.CompleteToDo(id);

        return RedirectToPage();
    }

    public IActionResult OnPostAdd()
    {
        _todos.AddToDo(NewToDo);
        return RedirectToPage();
    }
}

Lister.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
@Html.AntiForgeryToken()

<div>
    <form asp-page-handler="Add">
        <input type="text" class="form-control" placeholder="Add new todo" asp-for="@Model.NewToDo" />
        <input type="submit" class="btn btn-success" value="Save" />
    </form>
</div>

<br />
<hr />
<br />

<div>
    <table class="table">
        <thead>
            <tr>
                <th>Complete</th>
                <th>Title</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var todo in @Model.AllToDos)
            {
                @if (todo.IsComplete)
                {
                    <tr>
                        <td colspan="2">
                            <span style="color: grey; text-decoration: line-through;">@todo.Title</span>
                        </td>
                    </tr>
                }
                else
                {
                    <form asp-page-handler="Complete" asp-route-id="@todo.Id">
                        <tr>
                            <td>@todo.Title</td>
                            <td><input type="submit" class="btn btn-primary" value="Complete" /></td>
                        </tr>
                    </form>
                }
            }
        </tbody>
    </table>
</div>

Lister.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lister.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lister.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Lister.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lister.Web
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>